name: walkerholic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.5
  #location : ^4.1.1
  provider : ^5.0.0
  #geocoding : ^2.0.0
  geolocator : ^7.0.3
  background_location: ^0.6.0
  shared_preferences : ^2.0.5
  flutter_polyline_points : ^0.2.1
  intl : ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  fluttertoast: ^8.0.7
  is_first_run: ^1.0.0
  http: ^0.13.3
  camera: ^0.8.1+3
  path_provider: ^2.0.2
  path: ^1.8.0
  permission_handler: ^8.1.0
  image_picker: ^0.8.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash : ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

flutter_native_splash:
  image : assets/loadings.gif
  color: "ffffff"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/img_gwang.jpg
     - assets/img_simin.jpg
     - assets/img_unitedn.jpg
     - assets/loadings.gif
     - assets/marker_simin.png
     - assets/marker_unitedn.png
     - assets/marker_gwang.png
     - assets/map_jin.png
     - assets/map_nam.png
     - assets/map_soo.png
     - assets/ic_icon.png
     - assets/simin_icon.png
     - assets/gwang_icon.png
     - assets/unitedn_icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
